package me.fabriciorby.nes.cpu;

import java.util.function.Supplier;
import java.util.stream.IntStream;

public record Instruction(String name, Supplier<Integer> operation,
                          Supplier<Integer> addressingMode, int totalCycles) {

    public int runAndGetCycles() {
        return IntStream.of(this.addressingMode.get(), this.operation.get(), this.totalCycles).sum();
    }

    boolean isIMP() {
        return this.name.endsWith("IMP");
    }

    public String getName() {
        return this.name;
    }

    public static Instruction[] getInstructions(Cpu cpu) {
        return new Instruction[] {
                        new Instruction("BRK IMM", cpu::BRK, cpu::IMM, 7), new Instruction("ORA IZX", cpu::ORA, cpu::IZX, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 8), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 3), new Instruction("ORA ZP0", cpu::ORA, cpu::ZP0, 3), new Instruction("ASL ZP0", cpu::ASL, cpu::ZP0, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 5), new Instruction("PHP IMP", cpu::PHP, cpu::IMP, 3), new Instruction("ORA IMM", cpu::ORA, cpu::IMM, 2), new Instruction("ASL IMP", cpu::ASL, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 4), new Instruction("ORA ABS", cpu::ORA, cpu::ABS, 4), new Instruction("ASL ABS", cpu::ASL, cpu::ABS, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6),
                        new Instruction("BPL REL", cpu::BPL, cpu::REL, 2), new Instruction("ORA IZY", cpu::ORA, cpu::IZY, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 8), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 4), new Instruction("ORA ZPX", cpu::ORA, cpu::ZPX, 4), new Instruction("ASL ZPX", cpu::ASL, cpu::ZPX, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6), new Instruction("CLC IMP", cpu::CLC, cpu::IMP, 2), new Instruction("ORA ABY", cpu::ORA, cpu::ABY, 4), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 7), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 4), new Instruction("ORA ABX", cpu::ORA, cpu::ABX, 4), new Instruction("ASL ABX", cpu::ASL, cpu::ABX, 7), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 7),
                        new Instruction("JSR ABS", cpu::JSR, cpu::ABS, 6), new Instruction("AND IZX", cpu::AND, cpu::IZX, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 8), new Instruction("BIT ZP0", cpu::BIT, cpu::ZP0, 3), new Instruction("AND ZP0", cpu::AND, cpu::ZP0, 3), new Instruction("ROL ZP0", cpu::ROL, cpu::ZP0, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 5), new Instruction("PLP IMP", cpu::PLP, cpu::IMP, 4), new Instruction("AND IMM", cpu::AND, cpu::IMM, 2), new Instruction("ROL IMP", cpu::ROL, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("BIT ABS", cpu::BIT, cpu::ABS, 4), new Instruction("AND ABS", cpu::AND, cpu::ABS, 4), new Instruction("ROL ABS", cpu::ROL, cpu::ABS, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6),
                        new Instruction("BMI REL", cpu::BMI, cpu::REL, 2), new Instruction("AND IZY", cpu::AND, cpu::IZY, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 8), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 4), new Instruction("AND ZPX", cpu::AND, cpu::ZPX, 4), new Instruction("ROL ZPX", cpu::ROL, cpu::ZPX, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6), new Instruction("SEC IMP", cpu::SEC, cpu::IMP, 2), new Instruction("AND ABY", cpu::AND, cpu::ABY, 4), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 7), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 4), new Instruction("AND ABX", cpu::AND, cpu::ABX, 4), new Instruction("ROL ABX", cpu::ROL, cpu::ABX, 7), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 7),
                        new Instruction("RTI IMP", cpu::RTI, cpu::IMP, 6), new Instruction("EOR IZX", cpu::EOR, cpu::IZX, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 8), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 3), new Instruction("EOR ZP0", cpu::EOR, cpu::ZP0, 3), new Instruction("LSR ZP0", cpu::LSR, cpu::ZP0, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 5), new Instruction("PHA IMP", cpu::PHA, cpu::IMP, 3), new Instruction("EOR IMM", cpu::EOR, cpu::IMM, 2), new Instruction("LSR IMP", cpu::LSR, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("JMP ABS", cpu::JMP, cpu::ABS, 3), new Instruction("EOR ABS", cpu::EOR, cpu::ABS, 4), new Instruction("LSR ABS", cpu::LSR, cpu::ABS, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6),
                        new Instruction("BVC REL", cpu::BVC, cpu::REL, 2), new Instruction("EOR IZY", cpu::EOR, cpu::IZY, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 8), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 4), new Instruction("EOR ZPX", cpu::EOR, cpu::ZPX, 4), new Instruction("LSR ZPX", cpu::LSR, cpu::ZPX, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6), new Instruction("CLI IMP", cpu::CLI, cpu::IMP, 2), new Instruction("EOR ABY", cpu::EOR, cpu::ABY, 4), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 7), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 4), new Instruction("EOR ABX", cpu::EOR, cpu::ABX, 4), new Instruction("LSR ABX", cpu::LSR, cpu::ABX, 7), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 7),
                        new Instruction("RTS IMP", cpu::RTS, cpu::IMP, 6), new Instruction("ADC IZX", cpu::ADC, cpu::IZX, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 8), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 3), new Instruction("ADC ZP0", cpu::ADC, cpu::ZP0, 3), new Instruction("ROR ZP0", cpu::ROR, cpu::ZP0, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 5), new Instruction("PLA IMP", cpu::PLA, cpu::IMP, 4), new Instruction("ADC IMM", cpu::ADC, cpu::IMM, 2), new Instruction("ROR IMP", cpu::ROR, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("JMP IND", cpu::JMP, cpu::IND, 5), new Instruction("ADC ABS", cpu::ADC, cpu::ABS, 4), new Instruction("ROR ABS", cpu::ROR, cpu::ABS, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6),
                        new Instruction("BVS REL", cpu::BVS, cpu::REL, 2), new Instruction("ADC IZY", cpu::ADC, cpu::IZY, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 8), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 4), new Instruction("ADC ZPX", cpu::ADC, cpu::ZPX, 4), new Instruction("ROR ZPX", cpu::ROR, cpu::ZPX, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6), new Instruction("SEI IMP", cpu::SEI, cpu::IMP, 2), new Instruction("ADC ABY", cpu::ADC, cpu::ABY, 4), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 7), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 4), new Instruction("ADC ABX", cpu::ADC, cpu::ABX, 4), new Instruction("ROR ABX", cpu::ROR, cpu::ABX, 7), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 7),
                        new Instruction("??? IMP", cpu::NOP, cpu::IMP, 2), new Instruction("STA IZX", cpu::STA, cpu::IZX, 6), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6), new Instruction("STY ZP0", cpu::STY, cpu::ZP0, 3), new Instruction("STA ZP0", cpu::STA, cpu::ZP0, 3), new Instruction("STX ZP0", cpu::STX, cpu::ZP0, 3), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 3), new Instruction("DEY IMP", cpu::DEY, cpu::IMP, 2), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 2), new Instruction("TXA IMP", cpu::TXA, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("STY ABS", cpu::STY, cpu::ABS, 4), new Instruction("STA ABS", cpu::STA, cpu::ABS, 4), new Instruction("STX ABS", cpu::STX, cpu::ABS, 4), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 4),
                        new Instruction("BCC REL", cpu::BCC, cpu::REL, 2), new Instruction("STA IZY", cpu::STA, cpu::IZY, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6), new Instruction("STY ZPX", cpu::STY, cpu::ZPX, 4), new Instruction("STA ZPX", cpu::STA, cpu::ZPX, 4), new Instruction("STX ZPY", cpu::STX, cpu::ZPY, 4), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 4), new Instruction("TYA IMP", cpu::TYA, cpu::IMP, 2), new Instruction("STA ABY", cpu::STA, cpu::ABY, 5), new Instruction("TXS IMP", cpu::TXS, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 5), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 5), new Instruction("STA ABX", cpu::STA, cpu::ABX, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 5),
                        new Instruction("LDY IMM", cpu::LDY, cpu::IMM, 2), new Instruction("LDA IZX", cpu::LDA, cpu::IZX, 6), new Instruction("LDX IMM", cpu::LDX, cpu::IMM, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6), new Instruction("LDY ZP0", cpu::LDY, cpu::ZP0, 3), new Instruction("LDA ZP0", cpu::LDA, cpu::ZP0, 3), new Instruction("LDX ZP0", cpu::LDX, cpu::ZP0, 3), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 3), new Instruction("TAY IMP", cpu::TAY, cpu::IMP, 2), new Instruction("LDA IMM", cpu::LDA, cpu::IMM, 2), new Instruction("TAX IMP", cpu::TAX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("LDY ABS", cpu::LDY, cpu::ABS, 4), new Instruction("LDA ABS", cpu::LDA, cpu::ABS, 4), new Instruction("LDX ABS", cpu::LDX, cpu::ABS, 4), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 4),
                        new Instruction("BCS REL", cpu::BCS, cpu::REL, 2), new Instruction("LDA IZY", cpu::LDA, cpu::IZY, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 5), new Instruction("LDY ZPX", cpu::LDY, cpu::ZPX, 4), new Instruction("LDA ZPX", cpu::LDA, cpu::ZPX, 4), new Instruction("LDX ZPY", cpu::LDX, cpu::ZPY, 4), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 4), new Instruction("CLV IMP", cpu::CLV, cpu::IMP, 2), new Instruction("LDA ABY", cpu::LDA, cpu::ABY, 4), new Instruction("TSX IMP", cpu::TSX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 4), new Instruction("LDY ABX", cpu::LDY, cpu::ABX, 4), new Instruction("LDA ABX", cpu::LDA, cpu::ABX, 4), new Instruction("LDX ABY", cpu::LDX, cpu::ABY, 4), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 4),
                        new Instruction("CPY IMM", cpu::CPY, cpu::IMM, 2), new Instruction("CMP IZX", cpu::CMP, cpu::IZX, 6), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 8), new Instruction("CPY ZP0", cpu::CPY, cpu::ZP0, 3), new Instruction("CMP ZP0", cpu::CMP, cpu::ZP0, 3), new Instruction("DEC ZP0", cpu::DEC, cpu::ZP0, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 5), new Instruction("INY IMP", cpu::INY, cpu::IMP, 2), new Instruction("CMP IMM", cpu::CMP, cpu::IMM, 2), new Instruction("DEX IMP", cpu::DEX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("CPY ABS", cpu::CPY, cpu::ABS, 4), new Instruction("CMP ABS", cpu::CMP, cpu::ABS, 4), new Instruction("DEC ABS", cpu::DEC, cpu::ABS, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6),
                        new Instruction("BNE REL", cpu::BNE, cpu::REL, 2), new Instruction("CMP IZY", cpu::CMP, cpu::IZY, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 8), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 4), new Instruction("CMP ZPX", cpu::CMP, cpu::ZPX, 4), new Instruction("DEC ZPX", cpu::DEC, cpu::ZPX, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6), new Instruction("CLD IMP", cpu::CLD, cpu::IMP, 2), new Instruction("CMP ABY", cpu::CMP, cpu::ABY, 4), new Instruction("NOP IMP", cpu::NOP, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 7), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 4), new Instruction("CMP ABX", cpu::CMP, cpu::ABX, 4), new Instruction("DEC ABX", cpu::DEC, cpu::ABX, 7), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 7),
                        new Instruction("CPX IMM", cpu::CPX, cpu::IMM, 2), new Instruction("SBC IZX", cpu::SBC, cpu::IZX, 6), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 8), new Instruction("CPX ZP0", cpu::CPX, cpu::ZP0, 3), new Instruction("SBC ZP0", cpu::SBC, cpu::ZP0, 3), new Instruction("INC ZP0", cpu::INC, cpu::ZP0, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 5), new Instruction("INX IMP", cpu::INX, cpu::IMP, 2), new Instruction("SBC IMM", cpu::SBC, cpu::IMM, 2), new Instruction("NOP IMP", cpu::NOP, cpu::IMP, 2), new Instruction("??? IMP", cpu::SBC, cpu::IMP, 2), new Instruction("CPX ABS", cpu::CPX, cpu::ABS, 4), new Instruction("SBC ABS", cpu::SBC, cpu::ABS, 4), new Instruction("INC ABS", cpu::INC, cpu::ABS, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6),
                        new Instruction("BEQ REL", cpu::BEQ, cpu::REL, 2), new Instruction("SBC IZY", cpu::SBC, cpu::IZY, 5), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 8), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 4), new Instruction("SBC ZPX", cpu::SBC, cpu::ZPX, 4), new Instruction("INC ZPX", cpu::INC, cpu::ZPX, 6), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 6), new Instruction("SED IMP", cpu::SED, cpu::IMP, 2), new Instruction("SBC ABY", cpu::SBC, cpu::ABY, 4), new Instruction("NOP IMP", cpu::NOP, cpu::IMP, 2), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 7), new Instruction("??? IMP", cpu::NOP, cpu::IMP, 4), new Instruction("SBC ABX", cpu::SBC, cpu::ABX, 4), new Instruction("INC ABX", cpu::INC, cpu::ABX, 7), new Instruction("??? IMP", cpu::XXX, cpu::IMP, 7),
                };
    }
}